# Generated by Django 5.0.3 on 2024-06-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_pianolesson_pianonote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pianonote',
            name='note',
            field=models.CharField(max_length=1000),
        ),
    ]
