# Generated by Django 5.0.3 on 2024-06-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_pianonote_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pianonote',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='pianonote',
            name='start_time',
        ),
    ]
